### ISSUE TITLE
Investigate numerical differences when using Coupling:Map and Coupling:Ramp 

### ISSUE THREAD

**Issue by pausz** [BrainDynamicsUSYD/nftsim#101]
@timysnoturtle found that when using Coupling:Ramp to define a constant input results in longer and larger transient oscillations than when using directly Coupling:Map.

**Comment by stuart-knock** [comment]
I've reproduced the reported issue, but so far failed to identify its cause. I have excluded the setting of `deltanu` and thus `nu` as a possible cause -- verified that they are set correctly in CouplingRamp. Reproduction notes follow.

## CouplingRamp - Failure to Produce Result Consistent with Map
A `Coupling` specified as `Ramp` with the `nus` at the breakpoints as all equal should be equivalent to one specified as `Map` with `nu` set to the same value as all the `nus`.

#### Two .conf files that should be Equivalent

*NOTE: these `.conf` files are written against branch [`deltanu-indexing`](https://github.com/stuart-knock/nftsim/tree/deltanu-indexing) on my repo, there is currently (2018-03-06) an open pull request (#157) against that branch.*

The files are identical, except for that one uses `Map` with `nu=0` and the other uses `Ramp` with all `nus=0`.

`test_coupling_ramp_map.conf`
```
Example configuration file for one-population neural field model,
with full space output for propagator.  Using Wave 5-point.
Time: 1.0 Deltat: 0.0001220703125
Nodes: 128

    Connection matrix:
From:  1  2 
To 1:  1  2  
To 2:  0  0  


Population 1: Excitatory
Length: 0.5
Q: 10
Firing: Function: Sigmoid Theta: 0.01292 Sigma: 0.0038 Qmax: 340
 Dendrite 1: alpha: 83 beta: 769
 Dendrite 2: alpha: 83 beta: 769

Population 2: Stimulation
Length: 0.5
 Stimulus: PulseRect - Onset: 0.75625 Node: 128 Amplitude: 0.06125 Width: 0.00390625

Propagator 1: Wave - Tau: 0 Range: 0.2 gamma: 30
Propagator 2: Map - 

Coupling 1:  Map - nu: 0
Coupling 2:  Map - nu: 1e-4

Output: Node: All
Population:
Dendrite:
Propagator: 1
Coupling:

```

`test_coupling_ramp_ramp0.conf`
```
Example configuration file for one-population neural field model,
with full space output for propagator.  Using Wave 5-point.
Time: 1.0 Deltat: 0.0001220703125
Nodes: 128

    Connection matrix:
From:  1  2 
To 1:  1  2  
To 2:  0  0  


Population 1: Excitatory
Length: 0.5
Q: 10
Firing: Function: Sigmoid Theta: 0.01292 Sigma: 0.0038 Qmax: 340
 Dendrite 1: alpha: 83 beta: 769
 Dendrite 2: alpha: 83 beta: 769

Population 2: Stimulation
Length: 0.5
 Stimulus: PulseRect - Onset: 0.75625 Node: 128 Amplitude: 0.06125 Width: 0.00390625

Propagator 1: Wave - Tau: 0 Range: 0.2 gamma: 30
Propagator 2: Map - 

Coupling 1:  Ramp - nus: 0 0 0 0 timepoints: 0.125 0.25 0.5 0.75
Coupling 2:  Map - nu: 1e-4

Output: Node: All
Population:
Dendrite:
Propagator: 1
Coupling:

```

#### Run them and Visual Compare from Matlab.
Place files above into `test/numerical/`, then run:

```matlab
%% Run two simulations that should be equivalent.
obj_ramp0 = nf.run('./test/numerical/test_coupling_ramp_ramp0.conf')
obj_map = nf.run('./test/numerical/test_coupling_ramp_map.conf')

%% Extract some time-series data to plot.  
[map_data map_time] = nf.extract(obj_map, {'Propagator.1.phi'}, [], [128]);
[ramp0_data ramp0_time] = nf.extract(obj_ramp0, {'Propagator.1.phi'}, [], [128]);

%% Over plot, should be identical.
figure
plot(map_time, map_data, 'k')
hold on
plot(obj_ramp0.time, ramp0_data, 'r')
lgd = legend({'Map' 'Ramp'})
title(lgd, 'Coupling')

%% PLot the difference, should be zero.
figure
plot(obj_map.time, map_data - ramp0_data)
title('Map minus Ramp')
```

![coupling_map_vs_ramp](https://user-images.githubusercontent.com/1515979/37014819-efd6b8d6-214e-11e8-93ad-0a2141d28d80.png)

![coupling_map_minus_ramp](https://user-images.githubusercontent.com/1515979/37014820-f2bb553e-214e-11e8-9d2d-7b9d965e94e5.png)

**Comment by pausz** [comment]
I followed the same procedure but using a simple model with one population and one self-connection:

The file using `Map` is  `test_coupling_map.conf`

```
Test configuration file for issue #101

Time: 0.15 Deltat: 0.0001
Nodes: 900

    Connection matrix:
From:  1  
To 1:  1   


Population 1: Excitatory
Length: 0.5
Q: 10
Firing: Function: Sigmoid Theta: 0.01292 Sigma: 0.0038 Qmax: 340
 Dendrite 1: alpha: 83 beta: 769


Propagator 1: Wave - Tau: 0 Range: 0.2 gamma: 30

Coupling 1:  Map - nu: 1e-4

Output: Node: 1 Start: 0 
Population: 
Dendrite: 
Propagator: 1
Coupling: 1  
```


and the file using `Ramp` is `test_coupling_ramp.conf`

```
Test configuration file for issue #101

Time: 0.15 Deltat: 0.0001
Nodes: 900

    Connection matrix:
From:  1  
To 1:  1   


Population 1: Excitatory
Length: 0.5
Q: 10
Firing: Function: Sigmoid Theta: 0.01292 Sigma: 0.0038 Qmax: 340
 Dendrite 1: alpha: 83 beta: 769


Propagator 1: Wave - Tau: 0 Range: 0.2 gamma: 30

Coupling 1:  Ramp - nus: 1e-4 1e-4 timepoints: 0.05 0.1

Output: Node: 1 Start: 0 
Population: 
Dendrite: 
Propagator: 1
Coupling: 1  
```

#### Execution and comparison of the results in Matlab

```Matlab
%% Run two simulations that should be equivalent.
obj_map = nf.run('./test/numerical/test_coupling_map.conf');
obj_ramp  = nf.run('./test/numerical/test_coupling_ramp.conf');

%% Extract some time-series data to plot.  
[map_data, ~] = nf.extract(obj_map, {'Propagator.1.phi'}, [], [1]);
[ramp_data, ~] = nf.extract(obj_ramp, {'Propagator.1.phi'}, [], [1]);

[map_nu, map_time] = nf.extract(obj_map, {'Coupling.1.nu'}, [], [1]);
[ramp_nu, ramp_time] = nf.extract(obj_ramp, {'Coupling.1.nu'}, [], [1]);

%% Over plot, should be identical.
figure
plot(map_time, map_data, 'k')
hold on
plot(obj_ramp.time, ramp_data, 'r')
lgd = legend({'Map', 'Ramp'});
title(lgd, 'Coupling: Propagator')


%% Overplot nus
figure
plot(map_time, map_nu, 'k')
hold on
plot(obj_ramp.time, ramp_nu, 'r')
lgd = legend({'Map', 'Ramp'});
title(lgd, 'Coupling: Propagator')

%% Plot the difference, should be zero.
figure
subplot(2,1,1)
plot(obj_map.time, map_data - ramp_data)
subplot(2,1,2)
plot(obj_map.time, map_nu - ramp_nu)
title('Map minus Ramp')
```

![screenshot from 2018-04-03 15-47-53](https://user-images.githubusercontent.com/1563810/38231698-1675c5d6-3757-11e8-9fb4-816f379497ba.png)
![screenshot from 2018-04-03 15-48-54](https://user-images.githubusercontent.com/1563810/38231697-164dff4c-3757-11e8-83b5-353556aa51ed.png)
![screenshot from 2018-04-03 15-50-05](https://user-images.githubusercontent.com/1563810/38231695-16215ce4-3757-11e8-8513-9ff69103741c.png)
![screenshot from 2018-04-03 15-52-34](https://user-images.githubusercontent.com/1563810/38231692-15d2942e-3757-11e8-9b37-45f63d219189.png)


```Matlab
>> sum(map_nu - ramp_nu)

ans =

     0
```
These tests were done with master branch at commit 19abe3c55ed2b85c1265df756678827e986a86af
