### ISSUE TITLE
Documentation: wiki, users manual content and dev documentation

### ISSUE THREAD

**Issue by RomeshA** [BrainDynamicsUSYD/nftsim#7]
Manual - Information about the the base classes and some derived classes, configuration files, usage of +nf module.

Wiki - Information about github, project distribution, extra tutorials, setting up the environment

**Comment by pausz** [comment]
This issue has been addressed. The wiki has information about setting up NFTsim under different OS, how to contribute code, etc. The User Manual focuses on how to use NFTsim.
